import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  CoreAssistantMessage,
  CoreMessage,
  CoreToolMessage,
  CoreUserMessage,
} from "ai";

export function createUserMessage(content: string): CoreUserMessage {
  return {
    role: "user",
    content: [
      {
        type: "text",
        text: content,
      },
    ],
  };
}

export function createAssistantMessage(content: string): CoreAssistantMessage {
  return {
    role: "assistant",
    content: [
      {
        type: "text",
        text: content,
      },
    ],
  };
}

/**
A message that was generated during the generation process.
It can be either an assistant message or a tool message.
 */
type ResponseMessage = (CoreAssistantMessage | CoreToolMessage) & {
  /**
Message ID generated by the AI SDK.
 */
  id: string;
};

export function appendResponseMessages(
  messages: CoreMessage[],
  responseMessages: ResponseMessage[],
) {
  messages.push(...responseMessages);
}

export class MessageHistory {
  private history: CoreMessage[];
  private stateDir: string;
  constructor({ stateDir }: { stateDir: string }) {
    this.history = [];
    this.stateDir = stateDir;
  }

  get() {
    return [...this.history];
  }

  clear() {
    this.history.length = 0;
  }

  appendUserMessage(user: CoreUserMessage) {
    this.history.push(user);
  }

  appendAssistantMessage(assistant: CoreAssistantMessage) {
    this.history.push(assistant);
  }

  appendResponseMessages(responseMessages: ResponseMessage[]) {
    this.history.push(...responseMessages);
  }

  isEmpty() {
    return this.history.length === 0;
  }

  async save() {
    await mkdir(this.stateDir, { recursive: true });
    const timestamp = new Date().toISOString().replace(/:/g, "-");
    const fileName = `message-history-${timestamp}.json`;
    const filePath = join(this.stateDir, fileName);

    await writeFile(filePath, JSON.stringify(this.history, null, 2));
  }
}
